name: octodns

on:
  push:
    paths:
      - '*.yaml'
      - 'requirements.txt'
      - 'script/cibuild'
      - '.github/workflows/*.yml'

env:
  # Add the environment variables used by your provider.
  AWS_ACCESS_KEY_ID: ${{ secrets.route53_aws_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.route53_aws_secret_access_key }}

jobs:
  test:
    name: Test changes to DNS config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test changes to DNS config
        uses: solvaholic/octodns-sync@v2
        with:
          config_path: public.yaml
  deploy:
    name: Deploy changes to DNS config
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy changes to DNS config
        uses: solvaholic/octodns-sync@v2
        with:
          config_path: public.yaml
          doit: --doit
