name: octodns-sync

on:
  # Run when DNS changes are pushed to main
  push:
    branches:
      - main
    paths:
      - '*.yaml'
  # Run when manually triggered
  workflow_dispatch:
    inputs:
      doit:
        description: 'Really do it? Set "--doit" to do it, or another string to not do it.'
        required: true
        default: 'No'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.route53_aws_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.route53_aws_secret_access_key }}

jobs:
  octodns-sync:
    name: Test and deploy changes to DNS config
    runs-on: ubuntu-20.04
    environment: production
    steps:

      - name: Checkout the configuration repository
        uses: actions/checkout@v2

      - name: Validate DNS config, and plan for changes
        uses: solvaholic/octodns-sync@main
        # TODO: When no changes, skip the rest of this workflow?
        with:
          config_path: public.yaml
          # TODO: Add PR comment

      - name: Start deployment
        if: ${{ github.event.inputs.doit == '--doit' }}
        id: deployment
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ github.event.deployment.id }}
          env: public

      - name: Deploy DNS config changes
        if: ${{ steps.deployment.outputs.deployment_id > "" }}
        uses: solvaholic/octodns-sync@main
        with:
          config_path: ${{ steps.deployment.outputs.env }}.yaml
          doit: Not this time

      # name: Test the deployed DNS config
        # TODO: Run octodns-sync to confirm no changes to be made

      - name: Finish deployment
        if: ${{ steps.deployment.outputs.deployment_id > "" }}
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
