name: octodns-sync

on:
  # Run when DNS changes are pushed to any pull request
  pull_request:
    paths:
      - '*.yaml'
  # Run when manually triggered
  workflow_dispatch:
    inputs:
      doit:
        description: 'Really do it? Set "--doit" to do it, or another string to not do it.'
        required: true
        default: 'No'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.route53_aws_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.route53_aws_secret_access_key }}
  CONFIG_TO_USE: public.yaml

jobs:
  octodns-sync:
    name: Test and deploy changes to DNS config
    runs-on: ubuntu-20.04
    steps:

      - id: meta
        run: |
          # Set $_sha to the first 7 char of PR head SHA
          _sha="$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-7)"
          # Set output 'sha' to $_sha
          echo "::set-output name=sha::${_sha}"

      - name: Checkout ${{ github.repository }} from ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Validate ${{ env.CONFIG_TO_USE }}, and plan for changes
        id: validate
        uses: solvaholic/octodns-sync@b6675ce446abc9edcc2cb87575c9ac5e53811261
        # TODO: When no changes, skip the rest of this workflow?
        with:
          config_path: ${{ env.CONFIG_TO_USE }}

      - name: Find comment
        uses: peter-evans/find-comment@v1.2.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: Automatically generated by octodns-sync

      - name: Add ${{ env.CONFIG_TO_USE }} plan to pull request comment
        if: ${{ github.event_name == 'pull_request' }}
        id: prcomment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## OctoDNS Plan for `${{ steps.meta.outputs.sha }}` (${{ github.ref }})

            ${{ steps.validate.outputs.plan }}

            Automatically generated by octodns-sync
          edit-mode: replace

      - name: Start ${{ env.CONFIG_TO_USE }} deployment
        if: ${{ github.event.inputs.doit == '--doit' }}
        id: deployment
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ github.event.deployment.id }}
          # Note: This 'env' :point_down: is not a job or step env
          env: ${{ env.CONFIG_TO_USE }}

      - name: Deploy ${{ env.CONFIG_TO_USE }} (`--doit`)
        if: ${{ steps.deployment.outputs.deployment_id != 0 }}
        uses: solvaholic/octodns-sync@b6675ce446abc9edcc2cb87575c9ac5e53811261
        with:
          config_path: ${{ env.CONFIG_TO_USE }}
          doit: Not this time

      # name: Test ${{ env.CONFIG_TO_USE }} deployment
        # TODO: Run octodns-sync to confirm no changes to be made?

      - name: Finish ${{ env.CONFIG_TO_USE }} deployment
        if: ${{ steps.deployment.outputs.deployment_id != 0 }}
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          status: ${{ job.status }}
